#!/usr/bin/env bash
# days_per_batch sweep runner with crash "revive" logic, for finding the
# optimal loky-wave batch size on the remote machine, following the same
# methodology as dev/rechunk_sweep_remote.sh (chunk-size sweep, 2026-07-21).
#
# Unlike chunk size, days_per_batch is a direct CLI flag (--days-per-batch,
# canvodpy/src/canvodpy/cli/run.py:671-677) -- no config overlay needed for
# it. Each leg still gets its own overlay purely to give it a fresh
# stores_root_dir (so legs don't dedup-skip against each other's stores) and
# to hold chunk_strategies.gnss_store.epoch fixed at 180 -- the value the
# chunk-size sweep found best, so this sweep isn't confounded by it.
#
# For each value in DAYS_PER_BATCH_VALUES: generates a small overlay config
# (storage.stores_root_dir + a fixed epoch=180 chunk strategy), runs
# `canvodpy run --days-per-batch N --config <overlay>`, and if the process
# dies, restarts it WITHOUT --start so it resumes automatically from the
# last processed date (canvodpy run's documented behavior). After a value
# finishes (or exhausts its revive budget), archives .logs/ before moving to
# the next value so runs don't mix.
#
# Required:
#   STORES_ROOT_TEMPLATE   e.g. /home/nbader/shares/.../Stores_dpb\$dpb\$
#                           ($dpb$ is replaced with the actual value)
#
# Optional (defaults shown):
#   SITE=rosalia  START=2025087  END=2025114  (28 days)
#   DASHBOARD_HOST=0.0.0.0  DASHBOARD_PORT=3333
#   DAYS_PER_BATCH_VALUES="1 2 3 4"  -- capped well below the user-set [1, 14]
#     upper bound on purpose. rosalia is a 16-core/32GB box; PHASE 2 of
#     parsed_rinex_data_gen holds ALL days in a wave's parsed+augmented
#     datasets in memory simultaneously before the PHASE 3 batch write, so
#     peak RSS scales roughly linearly with days_per_batch. Measured from
#     the chunk180 sweep leg's own resource_sample telemetry on this same
#     machine (component/machine/performance.json, days_per_batch=1 at the
#     time): peak main+children RSS ~7.2GB. Linear extrapolation: 4 days
#     ~29GB (borderline, ~3GB headroom left), 7 days ~50GB and 14 days
#     ~101GB -- both guaranteed OOM on a 32GB box. There is NO runtime
#     memory guard to fall back on: processing.params.max_memory_gb is
#     purely advisory (MemoryMonitor never enforces it, ResourceSampler
#     only logs), so an unsafe value here just OOM-crashes and the revive
#     loop below will spin forever retrying a config that can never
#     succeed. Do not raise this above 4 without re-measuring headroom.
#   MAX_REVIVES=50  REVIVE_BACKOFF_S=30  REVIVE_BACKOFF_MAX_S=300
#   LOG_ARCHIVE_ROOT=.logs_archive  OVERLAY_DIR=dev/sweep_overlays
#
# NOTE: verify each leg's numbers the same way as the chunk-size sweep --
# check the per-leg store_stats log lines (component/icechunk.log) start
# near 0 manifests/snapshots, not continuing from the previous leg's. See
# dev/rechunk_sweep_remote.sh's header comment for the historical
# load_config() lru_cache bug this guards against (fixed, commit 26756184).
#
# Usage:
#   STORES_ROOT_TEMPLATE='/home/nbader/shares/climers/Studies/GNSS_Vegetation_Study/05_data/01_Rosalia/03_Rinex_Data/02_Rosalia_Development_Stores_dpb$dpb$' \
#     ./dev/days_per_batch_sweep_remote.sh
#
# Run under nohup/tmux/screen -- this is a long-running foreground loop.

set -uo pipefail  # no -e: revive loop must survive non-zero exits itself

: "${STORES_ROOT_TEMPLATE:?Set STORES_ROOT_TEMPLATE, e.g. /path/to/Stores_dpb\$dpb\$}"
SITE="${SITE:-rosalia}"
START="${START:-2025087}"
END="${END:-2025114}"
DASHBOARD_HOST="${DASHBOARD_HOST:-0.0.0.0}"
DASHBOARD_PORT="${DASHBOARD_PORT:-3333}"
DAYS_PER_BATCH_VALUES="${DAYS_PER_BATCH_VALUES:-1 2 3 4}"
FIXED_EPOCH="${FIXED_EPOCH:-180}"
MAX_REVIVES="${MAX_REVIVES:-50}"
REVIVE_BACKOFF_S="${REVIVE_BACKOFF_S:-30}"
REVIVE_BACKOFF_MAX_S="${REVIVE_BACKOFF_MAX_S:-300}"
LOG_ARCHIVE_ROOT="${LOG_ARCHIVE_ROOT:-.logs_archive}"
OVERLAY_DIR="${OVERLAY_DIR:-dev/sweep_overlays}"

mkdir -p "$LOG_ARCHIVE_ROOT" "$OVERLAY_DIR"

# --dashboard spawns a detached marimo subprocess that stays alive after
# canvodpy run exits (by design, so you can review a finished run) -- so a
# fixed port would collide with the previous leg's still-running dashboard.
# Increment per launch instead of trying to kill/reuse it.
port_offset=0

for DPB in $DAYS_PER_BATCH_VALUES; do
    stores_root="${STORES_ROOT_TEMPLATE//\$dpb\$/$DPB}"
    overlay="$OVERLAY_DIR/days_per_batch_${DPB}.yaml"

    cat > "$overlay" <<EOF
# Auto-generated by dev/days_per_batch_sweep_remote.sh -- deep-merged onto
# canvod-settings.yaml via --config, does not modify the main file.
processing:
  icechunk:
    chunk_strategies:
      gnss_store:
        epoch: ${FIXED_EPOCH}
        sid: -1
      vod_store:
        epoch: ${FIXED_EPOCH}
        sid: -1
  storage:
    stores_root_dir: ${stores_root}
EOF

    echo "=== days_per_batch=${DPB}: overlay -> ${overlay} (stores_root_dir=${stores_root}) ==="

    attempt=0
    backoff=$REVIVE_BACKOFF_S
    started=false

    while true; do
        attempt=$((attempt + 1))
        echo "=== days_per_batch=${DPB}: attempt ${attempt}/${MAX_REVIVES} ==="

        this_port=$((DASHBOARD_PORT + port_offset))
        port_offset=$((port_offset + 1))

        if ! $started; then
            uv run canvodpy run --site "$SITE" --start "$START" --end "$END" \
                --days-per-batch "$DPB" \
                --config "$overlay" \
                --dashboard --dashboard-host "$DASHBOARD_HOST" --dashboard-port "$this_port"
            status=$?
            started=true
        else
            # --start omitted: resumes from the last processed date in
            # this leg's store (see canvodpy run --help).
            uv run canvodpy run --site "$SITE" --end "$END" \
                --days-per-batch "$DPB" \
                --config "$overlay" \
                --dashboard --dashboard-host "$DASHBOARD_HOST" --dashboard-port "$this_port"
            status=$?
        fi
        echo "=== days_per_batch=${DPB}: dashboard on port ${this_port} ==="

        if [ "$status" -eq 0 ]; then
            echo "=== days_per_batch=${DPB}: completed cleanly after ${attempt} attempt(s) ==="
            break
        fi

        echo "=== days_per_batch=${DPB}: died (exit ${status}) on attempt ${attempt} ==="
        if [ "$attempt" -ge "$MAX_REVIVES" ]; then
            echo "=== days_per_batch=${DPB}: giving up after ${MAX_REVIVES} attempts -- moving on ==="
            break
        fi
        echo "=== days_per_batch=${DPB}: reviving in ${backoff}s ==="
        sleep "$backoff"
        backoff=$(( backoff * 2 > REVIVE_BACKOFF_MAX_S ? REVIVE_BACKOFF_MAX_S : backoff * 2 ))
    done

    if [ -d .logs ]; then
        label="days_per_batch${DPB}_$(date -u +%Y%m%dT%H%M%SZ)"
        echo "=== days_per_batch=${DPB}: archiving .logs -> ${LOG_ARCHIVE_ROOT}/${label} ==="
        mv .logs "${LOG_ARCHIVE_ROOT}/${label}"
    fi
done

echo "=== sweep complete: ${DAYS_PER_BATCH_VALUES} ==="
