#!/usr/bin/env bash
# Chunk-size sweep runner with crash "revive" logic, for validating
# dev/rechunk_benchmark_2026_07_20.md's synthetic findings against a real
# 60-day production run on the remote machine.
#
# For each chunk size in CHUNK_SIZES: generates a small overlay config
# (chunk_strategies.gnss_store.epoch + a distinct stores_root_dir so each
# chunk size gets its own fresh store), runs `canvodpy run` via --config,
# and if the process dies, restarts it WITHOUT --start so it resumes
# automatically from the last processed date (canvodpy run's documented
# behavior). After a chunk size finishes (or exhausts its revive budget),
# archives .logs/ before moving to the next chunk size so runs don't mix.
#
# Required:
#   STORES_ROOT_TEMPLATE   e.g. /home/nbader/shares/.../Stores_\$chunksize\$
#                           ($chunksize$ is replaced with the actual value)
#
# Optional (defaults shown):
#   SITE=rosalia  START=2025087  END=2025146
#   DASHBOARD_HOST=0.0.0.0  DASHBOARD_PORT=3333
#   CHUNK_SIZES="180 720 2880 5760 17280"
#   MAX_REVIVES=50  REVIVE_BACKOFF_S=30  REVIVE_BACKOFF_MAX_S=300
#   LOG_ARCHIVE_ROOT=.logs_archive  OVERLAY_DIR=dev/sweep_overlays
#
# Usage:
#   STORES_ROOT_TEMPLATE='/home/nbader/shares/climers/Studies/GNSS_Vegetation_Study/05_data/01_Rosalia/03_Rinex_Data/02_Rosalia_Development_Stores_$chunksize$' \
#     ./dev/rechunk_sweep_remote.sh
#
# Run under nohup/tmux/screen -- this is a long-running foreground loop.

set -uo pipefail  # no -e: revive loop must survive non-zero exits itself

: "${STORES_ROOT_TEMPLATE:?Set STORES_ROOT_TEMPLATE, e.g. /path/to/Stores_\$chunksize\$}"
SITE="${SITE:-rosalia}"
START="${START:-2025087}"
END="${END:-2025146}"
DASHBOARD_HOST="${DASHBOARD_HOST:-0.0.0.0}"
DASHBOARD_PORT="${DASHBOARD_PORT:-3333}"
CHUNK_SIZES="${CHUNK_SIZES:-180 720 2880 5760 17280}"
MAX_REVIVES="${MAX_REVIVES:-50}"
REVIVE_BACKOFF_S="${REVIVE_BACKOFF_S:-30}"
REVIVE_BACKOFF_MAX_S="${REVIVE_BACKOFF_MAX_S:-300}"
LOG_ARCHIVE_ROOT="${LOG_ARCHIVE_ROOT:-.logs_archive}"
OVERLAY_DIR="${OVERLAY_DIR:-dev/sweep_overlays}"

mkdir -p "$LOG_ARCHIVE_ROOT" "$OVERLAY_DIR"

for CHUNK in $CHUNK_SIZES; do
    stores_root="${STORES_ROOT_TEMPLATE//\$chunksize\$/$CHUNK}"
    overlay="$OVERLAY_DIR/chunk_${CHUNK}.yaml"

    cat > "$overlay" <<EOF
# Auto-generated by dev/rechunk_sweep_remote.sh -- deep-merged onto
# canvod-settings.yaml via --config, does not modify the main file.
processing:
  icechunk:
    chunk_strategies:
      gnss_store:
        epoch: ${CHUNK}
        sid: -1
  storage:
    stores_root_dir: ${stores_root}
EOF

    echo "=== chunk=${CHUNK}: overlay -> ${overlay} (stores_root_dir=${stores_root}) ==="

    attempt=0
    backoff=$REVIVE_BACKOFF_S
    started=false

    while true; do
        attempt=$((attempt + 1))
        echo "=== chunk=${CHUNK}: attempt ${attempt}/${MAX_REVIVES} ==="

        if ! $started; then
            uv run canvodpy run --site "$SITE" --start "$START" --end "$END" \
                --config "$overlay" \
                --dashboard --dashboard-host "$DASHBOARD_HOST" --dashboard-port "$DASHBOARD_PORT"
            status=$?
            started=true
        else
            # --start omitted: resumes from the last processed date in
            # this chunk size's store (see canvodpy run --help).
            uv run canvodpy run --site "$SITE" --end "$END" \
                --config "$overlay" \
                --dashboard --dashboard-host "$DASHBOARD_HOST" --dashboard-port "$DASHBOARD_PORT"
            status=$?
        fi

        if [ "$status" -eq 0 ]; then
            echo "=== chunk=${CHUNK}: completed cleanly after ${attempt} attempt(s) ==="
            break
        fi

        echo "=== chunk=${CHUNK}: died (exit ${status}) on attempt ${attempt} ==="
        if [ "$attempt" -ge "$MAX_REVIVES" ]; then
            echo "=== chunk=${CHUNK}: giving up after ${MAX_REVIVES} attempts -- moving on ==="
            break
        fi
        echo "=== chunk=${CHUNK}: reviving in ${backoff}s ==="
        sleep "$backoff"
        backoff=$(( backoff * 2 > REVIVE_BACKOFF_MAX_S ? REVIVE_BACKOFF_MAX_S : backoff * 2 ))
    done

    if [ -d .logs ]; then
        label="chunk${CHUNK}_$(date -u +%Y%m%dT%H%M%SZ)"
        echo "=== chunk=${CHUNK}: archiving .logs -> ${LOG_ARCHIVE_ROOT}/${label} ==="
        mv .logs "${LOG_ARCHIVE_ROOT}/${label}"
    fi
done

echo "=== sweep complete: ${CHUNK_SIZES} ==="
