---
title: canVOD Filename Convention
---
packet-beta
    0-2: "SIT"
    3: "T"
    4-5: "NN"
    6-8: "AGC"
    9-11: "_R_"
    12-15: "YYYY"
    16-18: "DOY"
    19-22: "HHMM"
    23: "_"
    24-26: "PPP"
    27: "_"
    28-30: "SSS"
    31: "_"
    32-33: "CC"
    34: "."
    35-37: "TTT"
